const List dyk = [
  'The brain activity produced by cocaine addiction was found to be identical to brain activity from pornography addiction in a 2011 study.',
  'A 2004 study found similar brain activity findings for methamphetamine addiction and pornography addiction.',
  'Compulsive pornography use has a devastating effect on the brain\'s reward system, similar to drug abuse.',
  'Pornography-related cues activate the same brain regions associated with drug craving in individuals with a history of pornography use.',
  'Engaging in pornography can flood the brain with an unhealthy amount of dopamine, leading to an unhealthy cycle of needing more and more of the behavior to get the same dopamine hit.',
  'High-intensity porn, such as content with more than two people, BDSM, or violence, can lead to amplified dopamine surges.',
  'Pornography functions as a "super stimulus" because it slightly exceeds stimuli typically seen in nature, making it virtually irresistible.',
  'Young males are particularly susceptible to pornography\'s super stimulus effect because male sexuality is highly visually oriented.',
  'The human brain, especially in individuals aged 0 to 25, is incredibly plastic and highly modified by experience.',
  'High-intensity pornography can "wire" neurons in a young brain, setting incredibly high thresholds for what is considered stimulating, not just sexually but mentally.',
  'It is a common pattern for pornographic usage to become more fetishistic over time, as this progression keeps the novelty alive but is considered a very dangerous development.',
  'Brain scans of sex addicts show areas that are overactive or underactive, indicating a brain problem.',
  'An 18-year-old sex addict\'s brain scan showed decreased blood flow to the prefrontal cortex compared to a normal brain.',
  'The prefrontal cortex, which acts as the "CEO" of the brain and controls decision-making, shows low activation in sex addict brains, similar to that seen in cocaine addiction.',
  'Addictive behaviors like porn increase dopamine very fast, leading to deeper and faster drops below baseline, resulting in increased pain and discomfort.',
  'Fast dopamine spikes from addictive behaviors train the brain to crave immediate pleasure, making it harder to enjoy activities that offer slower, more lasting rewards, like reading.',
  'Pornography can lead to erectile dysfunction.',
  'The brain learning to be aroused by watching others have sex may not translate to arousal during one-on-one interactions with a real partner, especially for young people consuming a lot of pornography.',
  'Mary Harrington\'s "law of fap entropy" suggests that the content one initially uses will become progressively more intense over time, requiring increasing "wildness" for a decreasing stimulus.',
  'Due to the Coolidge effect, the constant introduction of new virtual partners in pornography can decrease sensitivity to natural rewards, including the novelty of a new human partner.',
  'Individuals who regularly consume pornography may find themselves seeking out more extreme content over time to achieve the same dopamine hit.',
  'In some extreme cases, the constant introduction of new virtual partners through pornography may temporarily alter a person\'s sexual orientation.',
  'Young adults who report using pornography more frequently tend to have higher levels of relationship and sexual dissatisfaction.',
  'It can be quite difficult to establish a sexual relationship with an actual partner if one has been socialized into pornography sexuality.',
  'Pornography can establish a set of expectations that may not align well with real-world sexual experiences.',
  'Pornography can train the brain to evoke arousal by observing sex rather than actively participating, effectively turning one into a voyeur.',
  'Excessive masturbation can lead to preferring masturbation over sex and difficulties with ejaculation and enjoyment during partnered sex.',
  'Masturbation addiction can have physical side effects and lead to physical withdrawals, making it incredibly difficult to stop.',
  'The physical drive to continue masturbating is linked to the pleasurable feeling of semen leaving the penis.',
  'One individual reported daily left testicle ache and dangerously enlarged varicose veins in their testicles after fapping twice a day for five years.',
  'Excessive masturbation can cause tissue damage and urination problems.',
  'Pornography can contribute to low self-esteem, social anxiety, lack of confidence, and depression.',
  'Pornography addiction is considered a massive global problem, potentially exceeding alcoholism in prevalence, and is a factor in divorce.',
  'People who experience severe negative effects from pornography overuse often also exhibit signs of mental illness, suggesting underlying issues that contribute to negative sexual preferences.',
  'C.S. Lewis suggested masturbation can "sterilize" the faculties of love and imagination by turning individuals inward, making it harder to connect with real women.',
  'Masturbation can foster a harmful use of imagination, providing a substitute for virtues and successes that should be pursued in the real world.',
  'Attempts to manage sexual habits, such as masturbating only to thoughts of a spouse, can ironically serve as a "gateway back into old patterns."',
  'True freedom from addiction involves not being controlled by desire at all.',
  'Pornography and internet videos are cited as factors capable of ruining one\'s life, even for individuals who have successfully overcome other addictions like smoking or drinking.',
  'Quitting addictive behaviors can lead to dopamine withdrawals, resulting in symptoms such as crying and depression.',
  'The prefrontal cortex for decision-making shows low activation in sex addict brains.',
  'Pornography can take over the mind.',
  'The "Research" page contains extensive research archives on porn\'s effects.',
  'The ICD-11 includes "Compulsive Sexual Behavior Disorder" (CSBD) as a medical diagnosis.',
  'Neuroscience-based studies generally support the addiction model for porn users and sex addicts, mirroring substance addiction findings.',
  'Over 50 studies link porn use/porn addiction to sexual problems and lower arousal to sexual stimuli, with 7 demonstrating causation.',
  'Over 60 studies report findings consistent with escalation of porn use (tolerance), habituation, and withdrawal symptoms.',
  'At least 30 studies falsify the claim that sex & porn addicts "just have high sexual desire."',
  'Over 80 studies link porn use to less sexual and relationship satisfaction, with all male studies reporting poorer outcomes.',
  'Over 85 studies link porn use to poorer mental-emotional health and cognitive outcomes.',
  'Over 40 studies link porn use to "un-egalitarian attitudes" toward women and sexist views.',
  'Exposure to sexualized media is associated with higher levels of body dissatisfaction, self-objectification, and tolerance of sexual violence toward women.',
  'Pornography consumption is associated with sexual aggression, stronger for verbal than physical aggression.',
  'Rape rates have been rising, debunking claims that porn use reduces them.',
  'Youth who consume pornography may develop unrealistic sexual values and beliefs.',
  'Problematic Internet pornography use is a condition that may be diagnosed under the ICD-11 category "other specified disorders due to addictive behaviors."',
  'Problems with cybersex addiction are predicted by indicators of sexual arousal and craving to Internet pornographic cues, not by real-life sexual contacts.',
  'Individuals with problematic use often show higher scores for craving, attentional impulsivity, and delayed discounting.',
  '“Withdrawal” and “Loss of pleasure” are important indicators of problematic hypersexuality (PH), not orgasm frequency or excessive sexual drive.',
  'Increased sexual desire and higher sexual frequency are not good indicators of problematic hypersexuality.',
  'Internet porn erodes normal sexual desire, leaving users less responsive to pleasure.',
  'Studies assessing young male sexuality since 2010 report historic levels of sexual dysfunctions, including low libido and ED.',
  'Erectile dysfunction rates for men under 40 ranged from 14% to 37% after 2006 (streaming porn advent).',
  'Terminating Internet pornography use is sometimes sufficient to reverse negative effects.',
  'Addictive masturbation, often accompanied by cyber-porn dependency, plays a role in erectile dysfunction or coital anejaculation.',
  'PIED (pornography induced erectile dysfunction) is a phenomenon where sexual arousal becomes exclusively associated with extreme and fast-paced pornography.',
  'PIED results in inability to maintain an erection with a real-life partner.',
  'Pornography can create an ideal woman, leading to dissatisfaction with real partners because they don\'t match expectations.',
  '“You get bored, it’s like those blue movies; you’ve got to get stronger and stronger stuff all the time, to cheer yourself up.”',
  'Sexual response can become conditional on a narrow set of stimuli from masturbation with erotica/fantasy, exacerbating difficulties with a partner.',
  'Increasing reliance on viewing/recalling porn images to become aroused.',
  'Tolerance to arousal effects of particular material leads to searching for new, more extreme material.',
  'Arousal problems with partners often coincide with porn use.',
  'Latency (ages 6-12) exposure to sexually explicit material (SEM) was a significant predictor of adult sexual dysfunctions.',
  'In couples where only one partner used pornography, there were more problems related to male arousal and negative female self-perception.',
  'Many self-help group members complained about increased impotence and lack of ejaculation.',
  'Problematic Internet porn use was associated with reduced erectile function and reduced overall sexual satisfaction.',
  '49% of men reported viewing porn not previously interesting or considered disgusting.',
  'Couples where no one used porn reported more relationship satisfaction than those with individual users.',
  'Higher porn use was related to poorer sexual function, more sexual problems, and a "worse sex life."',
  'Frequent pornography consumption was directly related to a preference for pornographic rather than partnered sexual excitement.',
  'Early exposure to graphic sexual material (before age 13) has increased, contributing to delayed ejaculation (DE).',
  'As men sensitize sexual arousal to pornography, real-life sex may not activate neurological pathways for ejaculation/erection.',
  'Low sexual desire, reduced satisfaction in sexual intercourse, and ED are increasingly common in young populations, with psychogenic ED on the rise.',
  'Pornography is cited as the principal cause of compulsive masturbatory behavior, cybersex addiction, and ED.',
  'Porn addiction was significantly related to poorer erections.',
  'Men who used porn almost daily or more had ED rates of 44%.',
  'Regular porn users scored 50% lower on sexual desire and 30% lower on erectile functioning in a study of 19-25 year old males.',
  'More frequent porn use linked to difficulty achieving orgasm through sexual insecurity.',
  'A highly significant relationship was found between time spent watching porn and increasing difficulty with erectile function with a partner.',
  'Only 65% of men felt sex with a partner was more exciting than watching porn.',
  '20% felt they needed to watch more extreme porn for same arousal level.',
  'Problematic online porn use negatively affected intimate and sexual lives of treatment-seeking men, including inability to share intimacy.',
  'Almost all patients (150 Italian men with ED) used WebPorn as a stimulus for masturbation.',
  'Compulsive pornography use is associated with less erectile function and low ejaculatory control in young men.',
  'Men who consumed pornography had higher median values of "Hostile Sexism" than those who did not.',
  'Mass exposure to pornography resulted in a loss of compassion toward women as rape victims and women in general.',
  'Increased past pornography consumption was significantly associated with less egalitarian attitudes toward women and more hostile sexism among men.',
  'Problematic online pornography use is a clinically relevant phenomenon.',
  'Abstinence for 90 days (a "reboot") is recommended to reset the brain.'
];