const List<String> tips = [
  'Remember, every day is a new beginning. Consciously decide to change. You\'ve got this!',
  'Confess the problem to loved ones or a support group; secrecy empowers addiction.',
  'Start by eliminating pornography. If cold turkey is too difficult, gradually wean off by using non-pornographic materials (e.g., bikini magazines) until they become boring. Buying more is prohibited.',
  'Stop using external stimuli for fapping (sounds/images). If you must, do it in the dark, allowing your mind to wander freely.',
  'Fill your schedule with other activities and tasks to avoid idle time that could lead to the habit.',
  'Spend time around people, even working in public places like a library or cafe.',
  'Write down your reasons for quitting and revisit them often. Remind yourself of them when temptations arise.',
  'Develop new interests – learn to code, play an instrument, start a business, learn languages, or find new social hobbies like pottery or parkour.',
  'Exercise regularly and vigorously to boost your mood, energy, and overall well-being. Work out to the point of exhaustion to leave no energy for fapping.',
  'Address your mental health. Addiction is often a symptom of deeper issues like loneliness or a poor mental state.',
  'Practice mindfulness and meditation to control urges and regain clarity of thought.',
  'Identify and avoid triggers that make you want to relapse.',
  'If quitting cold turkey is too difficult, consider gradually reducing frequency, for example, by setting a structured schedule for yourself.',
  'Use a calendar (physical or digital) to track your progress and plan your "clean" days.',
  'If you experience a relapse, do not feel guilty. Learn from what went wrong, understand the triggers, and recommit to your plan.',
  'Start confronting your shame and social fears. Write down lists of everything that has made you feel shame in your life.',
  'Forgive yourself and others for past mistakes. Your future is more important than dwelling on the past.',
  'Actively overcome your social fears (e.g., public speaking, interacting with new people) to build internal strength and control.',
  'Focus on building a meaningful life. True freedom from the habit often comes when your life feels purposeful and has direction.',
  'Cultivate inner strength and self-discipline, rather than relying solely on external structures or avoiding temptations.',
  'Be aware of the potential physical and psychological effects of excessive fapping, such as erectile dysfunction, brain fog, low energy levels, or even physical pain.',
  'You have successfully finished the challenge! Stay hydrated and maintain a healthy diet; this supports your overall well-being, energy levels, and mental clarity.',
];